export default {
	CHANGE_BG_COLOUR: 'CHANGE_BG_COLOUR',
	CHANGE_OPACITY: 'CHANGE_OPACITY',
	ADD_LAYER: 'ADD_LAYER',
	REMOVE_LAYER: 'REMOVE_LAYER',
	DECREASE_Z_INDEX: 'DECREASE_Z_INDEX',
	INCREASE_Z_INDEX: 'INCREASE_Z_INDEX',
	TO_BOTTOM_Z_INDEX: 'TO_BOTTOM_Z_INDEX',
	TO_TOP_Z_INDEX: 'TO_TOP_Z_INDEX',
	TOGGLE_FIX_TARGET_COLOUR: 'TOGGLE_FIX_TARGET_COLOUR',
}