export default {
	CHANGE_FROM_CURRENCY: "CHANGE_FROM_CURRENCY",
	SWAP_CURRENCY: "SWAP_CURRENCY",
	CHANGE_TO_CURRENCY: "CHANGE_TO_CURRENCY",
	CHANGE_CURRENCY_RATE: "CHANGE_CURRENCY_RATE",
	CLICK_NUMBER_PAD: "CLICK_NUMBER_PAD",
	CLEAR_VALUE_LIST: "CLEAR_VALUE_LIST",
	SAVE_VALUE: "SAVE_VALUE",
	DELETE_ROW: "DELETE_ROW",
}